### ISSUE TITLE
Steps to build

### ISSUE THREAD

**Issue by dave1981** [colinmollenhour/mariadb-galera-swarm#87]
Excuse me if this is not the right place to write, but what are the right steps to build the image and deploy it to a private repository for testing?
I tried to do it on my own but I got some errors. First of all, I had to execute the command `chmod +x *.sh` to make the sh files executable.
The problem now is that when i try to deploy to a stack, in the logs I see the message `/usr/local/bin/run-upgrades.sh: waiting for server to become available...` and, after some lines with the same message, 
`Received TERM|INT signal.
Shutting down...
MariaDB exited with return code (0)`

Is it possible to expose some other ports? I have to use 8080 for another container with tomcat

**Comment by colinmollenhour** [comment]
Hi Dave,

These sounds like implementation issues so this isn't really the right place for these questions, I only intend to support bug fixes and improvements via github. That said...

The run-upgrades.sh error is not a problem, you can ignore those log messages. Since it says "Received TERM|INT" it sounds like Docker signaled the container to shut down and the reason is unknown to me.
It is ok if the internal ports conflict with your other containers, docker lets you map them to other ports. E.g. `-p 54321:8080`.
